---
- hosts: localhost
  gather_facts: no
  name: GITHUB backups for local work
  tasks:
  - name: copy sources from github
    git: 
      repo: "{{ item }}"
      dest: ~/src/snippets/fedora-ansible
      force: yes
    loop:
      - https://github.com/fabaff/fedora-ansible
      - https://github.com/pgporada/ansible-role-vim.git
      - https://gitlab.com/jsherman82/ansible_article.git
      - https://github.com/j1mc/ansible-fedora-workstation-setup.git
      - https://github.com/docent-net/fedora-desktop-ansible.git
      - https://github.com/docent-net/systemd-workshop.git
      - https://github.com/henrysher/fedora-infra-ansible.git
      - https://github.com/bertvv/ansible-role-fedora.git
      - https://github.com/geerlingguy/docker-fedora27-ansible.git
      - https://github.com/geerlingguy/ansible-for-devops.git
      - https://github.com/geerlingguy/ansible-vagrant-examples.git