---
- hosts: localhost
  become: true
  gather_facts: True
  name: install rpmfusion repositories
  tasks:
  - name: install packages 
    dnf: 
      name: "{{ rpms }}"
      state: present
    vars:
      rpms:
      - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
